server.port=8086
spring.application.name=Factura-Service

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@ioe75gv6wcjpehj4_high?TNS_ADMIN=/ruta/a/tu/Wallet_de_produccion
spring.datasource.username=PROD_USER
spring.datasource.password=PROD_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.cl.duoc.factura=INFO

usuario-service.url=http://usuarios.prod.com

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
