# Puerto del servidor
server.port=8086

# Nombre identificador para ambiente de pruebas
spring.application.name=Factura-Service-Test

# Configuración base de datos Oracle (puede ser la misma u otra si tienes otra para test)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@ioe75gv6wcjpehj4_high?TNS_ADMIN=C:/Users/ALUMNO/Documents/WalletFullstack/Wallet_IOE75GV6WCJPEHJ4
spring.datasource.username=ADMIN
spring.datasource.password=Molly123456..

# Hibernate para pruebas (puede usar create-drop si quieres limpiar)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Logging
logging.level.root=INFO
logging.level.cl.duoc.factura=DEBUG

# Swagger para pruebas
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Servicio externo (usuarios)
usuario-service.url=http://localhost:8080

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
