# Configuración específica para desarrollo
server.port=8086

# Base de datos desarrollo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@ioe75gv6wcjpehj4_high?TNS_ADMIN=C:/Users/ALUMNO/Documents/WalletFullstack/Wallet_IOE75GV6WCJPEHJ4
spring.datasource.username=ADMIN
spring.datasource.password=Molly123456..

# Hibernate desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Logging desarrollo
logging.level.root=INFO
logging.level.cl.duoc.factura=DEBUG

# URL Swagger UI (específica para dev)
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Servicios externos desarrollo
usuario-service.url=http://localhost:8080