# Configuración común a todos los perfiles
spring.application.name=Factura-Service
spring.profiles.active=dev

# Configuración común de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.info.title=${spring.application.name} API
springdoc.info.version=1.0.0

# Configuración común de Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always