# Configuración básica
spring.application.name=Cupon-Service
spring.profiles.active=dev

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.info.title=${spring.application.name} API
springdoc.info.version=1.0.0

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always