server.port=8091
spring.application.name=Cupon-Service

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//oracle-prod:1521/ORCLPDB
spring.datasource.username=CUPON_PROD
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Config específica
cupon.validez-dias=30
cupon.max-usos=5
logging.level.root=INFO

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never