# Puerto del servidor
server.port=8090

# Nombre identificador para ambiente de pruebas
spring.application.name=Cupon-Service-Test

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@ioe75gv6wcjpehj4_high?TNS_ADMIN=C:/Users/ALUMNO/Documents/WalletFullstack/Wallet_IOE75GV6WCJPEHJ4
spring.datasource.username=ADMIN
spring.datasource.password=Molly123456..

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Config específica
cupon.validez-dias=1
cupon.max-usos=9999
# Logging
logging.level.root=INFO
logging.level.cl.duoc.factura=DEBUG

# Swagger para pruebas
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always